language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install flake8  
script:
- "flake8 --show-source --ignore=W293,E201,E202,E501,W291,E221,E231,E203,W391,E303,E251,E731 --exclude=\"epd*,venv/*\""

